export const legendListSelf = [
  {
    id: '1',
    label: '供水',
    titleStatus: false, // 用于控制该标题下所有图层显隐，true表示图层均显示，false表示均隐藏
    eventPopup: true, // 用于控制调度中心模块全部事件点弹窗，保存在第一个图例模块下，与该图例模块没有关联
    options: [
      {
        id: 'map_supply_pipe_distribute',
        label: '配水管线*',
        style_str: '',
        icon: 'assets/map/mapLegend/配水管线',
        iconGray: 'assets/map/mapLegend/管线_灰',
        clickFlag: false, // false表示当前图例为点亮状态
        clickColor: '#FFE24E',
      },
      {
        id: 'map_supply_pipe_circulating',
        label: '回水管线*',
        style_str: '',
        icon: 'assets/map/mapLegend/回水管线',
        iconGray: 'assets/map/mapLegend/管线_灰',
        clickFlag: false,
        clickColor: '#9F6EFF',
      },
      {
        id: 'map_supply_pipe_delivery',
        label: '输水管线*',
        style_str: '',
        icon: 'assets/map/mapLegend/输水管线',
        iconGray: 'assets/map/mapLegend/管线_灰',
        clickFlag: false,
        clickColor: '#FEBA87',
      },
      {
        id: 4,
        label: '原水管线',
        style_str: '',
        icon: 'assets/map/mapLegend/原水管线',
        iconGray: 'assets/map/mapLegend/管线_灰',
        clickFlag: true,
      },
      {
        id: 'map_waterwork',
        label: '供水厂*',
        style_str: '',
        icon: 'assets/map/mapLegend/供水厂',
        iconGray: 'assets/map/mapLegend/水厂_灰',
        clickFlag: false,
      },
      {
        id: 'map_supply_pump',
        label: '给水加压泵站*',
        style_str: '',
        icon: 'assets/map/mapLegend/给水加压泵站',
        iconGray: 'assets/map/mapLegend/泵站_灰',
        clickFlag: false,
      },
      {
        id: 6,
        label: '原水泵站',
        style_str: '',
        icon: 'assets/map/mapLegend/原水泵站',
        iconGray: 'assets/map/mapLegend/泵站_灰',
        clickFlag: true,
      },
      {
        id: 'map_supply_valve',
        label: '阀门*',
        style_str: '',
        icon: 'assets/map/mapLegend/阀门',
        iconGray: 'assets/map/mapLegend/阀门_灰',
        clickFlag: false,
      },
      {
        id: 'map_supply_firehydrant',
        label: '消火栓*',
        style_str: '',
        icon: 'assets/map/mapLegend/消火栓',
        iconGray: 'assets/map/mapLegend/消火栓_灰',
        clickFlag: false,
      },
    ],
  },
  {
    id: '4',
    label: '监测',
    titleStatus: false,
    allPopupShow: true, // 用于控制监测点所有图层popup开关
    options: [
      {
        id: '压力监测(供)*',
        label: '压力监测(供)*',
        style_str: '',
        icon: 'assets/map/mapLegend/压力监测',
        iconGray: 'assets/map/mapLegend/压力监测_灰',
        clickFlag: false,
      },
      {
        id: "压力监测(再生)*",
        label: "压力监测(再生)*",
        style_str: "",
        icon: "assets/map/mapLegend/压力监测再生",
        iconGray: "assets/map/mapLegend/压力监测_灰",
        clickFlag: false,
      },
      {
        id: '流量计(供)*',
        label: '流量计(供)*',
        style_str: '',
        icon: 'assets/map/mapLegend/流量计',
        iconGray: 'assets/map/mapLegend/流量计_灰',
        clickFlag: false,
      },
      {
        id: "流量计(再生)*",
        label: "流量计(再生)*",
        style_str: "",
        icon: "assets/map/mapLegend/流量计再生",
        iconGray: "assets/map/mapLegend/流量计_灰",
        clickFlag: false,
      },
      {
        id: 3,
        label: '水质',
        style_str: '',
        icon: 'assets/map/mapLegend/水质',
        iconGray: 'assets/map/mapLegend/水质_灰',
        clickFlag: true,
      },
      // {
      //   id: 4,
      //   label: "水位计",
      //   style_str: "",
      //   icon: "assets/map/mapLegend/水位计",
      //   iconGray: "assets/map/mapLegend/水位计_灰",
      //   clickFlag: true
      // },
      // {
      //   id: 5,
      //   label: "远传水表",
      //   style_str: "",
      //   icon: "assets/map/mapLegend/远传水表",
      //   iconGray: "assets/map/mapLegend/远传水表_灰",
      //   clickFlag: true
      // },
      // {
      //   id: 6,
      //   label: "积水监测",
      //   style_str: "",
      //   icon: "assets/map/mapLegend/积水监测",
      //   iconGray: "assets/map/mapLegend/积水监测_灰",
      //   clickFlag: true,
      // },
      // {
      //   id: 7,
      //   label: "视频",
      //   style_str: "",
      //   icon: "assets/map/mapLegend/视频",
      //   iconGray: "assets/map/mapLegend/视频_灰",
      //   clickFlag: true,
      // },
      // {
      //   id: 8,
      //   label: "智能井盖",
      //   style_str: "",
      //   icon: "assets/map/mapLegend/智能井盖",
      //   iconGray: "assets/map/mapLegend/智能井盖_灰",
      //   clickFlag: true
      // },
      // {
      //   id: 9,
      //   label: "液位计",
      //   style_str: "",
      //   icon: "assets/map/mapLegend/液位计",
      //   iconGray: "assets/map/mapLegend/液位计_灰",
      //   clickFlag: true,
      // },
    ],
  },
]
