// import { gisDomain } from '@/settings.js'
const commonPropertiesConfig = {
    gsPoint:[
        {
            name:"类型",
            value:'display'
        },{
            name:"口径",
            value:'caliber'
        },{
            name:"材质",
            value:'material'
        },{
            name:"位置",
            value:'adress'
        },{
            name:"埋深",
            value:'depth'
        },{
            name:"横坐标",
            value:'x'
        },{
            name:"纵坐标",
            value:'y'
        },{
            name:"地面高程",
            value:'floorelevation'
        },{
            name:"工程名称",
            value:'projectName'
        },{
            name:"工程编号",
            value:'projectId'
        },{
            name:"管网类型",
            value:'pipetype'
        }
    ],
    gsLine:[
        {
            name:"类型",
            value:'display'
        },{
            name:"口径",
            value:'caliber'
        },{
            name:"材质",
            value:'material'
        },{
            name:"是否明管",
            value:'isdhg'
        },{
            name:"位置",
            value:'adress'
        },{
            name:"工程名称",
            value:'projectName'
        },{
            name:"工程编号",
            value:'projectId'
        },{
            name:"特殊管线类型",
            value:'defdescription'
        }
    ],
    psPoint:[
        {
            name:"类型",
            value:'display'
        },{
            name:"口径",
            value:'caliber'
        },{
            name:"井尺寸",
            value:'jcc'
        },{
            name:"材质",
            value:'material'
        },{
            name:"位置",
            value:'adress'
        },{
            name:"埋深",
            value:'depth'
        },{
            name:"横坐标",
            value:'x'
        },{
            name:"纵坐标",
            value:'y'
        },{
            name:"地面高程",
            value:'floorelevation'
        },{
            name:"工程名称",
            value:'projectName'
        },{
            name:"工程编号",
            value:'projectId'
        },{
            name:"管网类型",
            value:'pipetype'
        }
    ],
    psLine:[
        {
            name:"类型",
            value:'display'
        },{
            name:"口径",
            value:'caliber'
        },{
            name:"材质",
            value:'material'
        },{
            name:"位置",
            value:'adress'
        },{
            name:"工程名称",
            value:'projectName'
        },{
            name:"工程编号",
            value:'projectId'
        },{
            name:"特殊管线类型",
            value:'defdescription'
        },{
            name:"起点埋深",
            value:'startdepth'
        },{
            name:"终点埋深",
            value:'enddepth'
        },{
            name:"断面尺寸",
            value:'inletSize'
        },{
            name:"压力类型",
            value:'pressType'
        }
    ]
}
const TypeList = {
    'YIL':{
        url:"/yhsw-map/mapYhMapComb/detail",
        name:"雨水口",
        system:"雨水",
        imgUrl:"/static/img/IntelligentDrainage/雨水0.png",
        info:commonPropertiesConfig.psPoint
    },
    'WIL':{
        url:"/yhsw-map/mapYhMapComb/detail",
        name:"污水口",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psPoint
    },
    'YPP':{
        url:"/yhsw-map/mapYhMapDrainpipe/detail",
        name:"雨水管线",
        system:"雨水",
        imgUrl:"/static/img/IntelligentDrainage/雨水0.png",
        info:commonPropertiesConfig.psLine
    },
    'WPP':{
        url:"/yhsw-map/mapYhMapDrainpipe/detail",
        name:"污水管线",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psLine
    },
    'PJG':{
        url:"/yhsw-map/mapYhMapDrainpipe/detail",
        name:"排江管",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psLine
    },
    'HPP':{
        url:"/yhsw-map/mapYhMapDrainpipe/detail",
        name:"雨污混合管线",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psLine
    },
    'XQY':{
        url:"/yhsw-map/mapYhMapDrainpipe/detail",
        name:"小区雨水管",
        system:"雨水",
        imgUrl:"/static/img/IntelligentDrainage/雨水0.png",
        info:commonPropertiesConfig.psLine
    },
    'XQW':{
        url:"/yhsw-map/mapYhMapDrainpipe/detail",
        name:"小区污水管",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psLine
    },

    'YST':{
        url:"/yhsw-map/mapYhMapDrainpump/detail",
        name:"雨水泵站",
        system:"雨水",
        imgUrl:"/static/img/IntelligentDrainage/雨水0.png",
        info:commonPropertiesConfig.psPoint
    },
    'WST':{
        url:"/yhsw-map/mapYhMapDrainpump/detail",
        name:"污水泵站",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psPoint
    },
    'SST':{
        url:"/yhsw-map/mapYhMapSupplypump/detail",
        name:"供水泵站",
        system:"供水",
        imgUrl:"/static/img/IntelligentDrainage/供水0.png",
        info:commonPropertiesConfig.gsPoint
    },
    'FHD':{
        url:"/yhsw-map/mapYhMapFirehydrant/detail",
        name:"消火栓",
        system:"供水",
        imgUrl:"/static/img/IntelligentDrainage/供水0.png",
        info:commonPropertiesConfig.gsPoint
    },

    'YWL':{
        url:"/yhsw-map/mapYhMapManhole/detail",
        name:"雨水检查井",
        system:"雨水",
        imgUrl:"/static/img/IntelligentDrainage/雨水0.png",
        info:commonPropertiesConfig.psPoint
    },
    'WWL':{
        url:"/yhsw-map/mapYhMapManhole/detail",
        name:"污水检查井",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psPoint
    },
    'HWL':{
        url:"/yhsw-map/mapYhMapManhole/detail",
        name:"雨污混合检查井",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psPoint
    },


    'SND':{
        url:"/yhsw-map/mapYhMapNode/detail",
        name:"供水节点",
        system:"供水",
        imgUrl:"/static/img/IntelligentDrainage/供水0.png",
        info:commonPropertiesConfig.gsPoint
    },
    'YND':{
        url:"/yhsw-map/mapYhMapNode/detail",
        name:"雨水节点",
        system:"雨水",
        imgUrl:"/static/img/IntelligentDrainage/雨水0.png",
        info:commonPropertiesConfig.psPoint
    },
    'WND':{
        url:"/yhsw-map/mapYhMapNode/detail",
        name:"污水节点",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psPoint
    },
    'HND':{
        url:"/yhsw-map/mapYhMapNode/detail",
        name:"雨污混合节点",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psPoint
    },
    
    'YOL':{
        url:"/yhsw-map/mapYhMapOutfall/detail",
        name:"雨水排放口",
        system:"雨水",
        imgUrl:"/static/img/IntelligentDrainage/雨水0.png",
        info:commonPropertiesConfig.psPoint
    },
    'WOL':{
        url:"/yhsw-map/mapYhMapOutfall/detail",
        name:"污水排放口",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psPoint
    },
    'SOL':{
        url:"/yhsw-map/mapYhMapOutfall/detail",
        name:"供水排放口",
        system:"供水",
        imgUrl:"/static/img/IntelligentDrainage/供水0.png",
        info:commonPropertiesConfig.gsPoint
    },
    'HOL':{
        url:"/yhsw-map/mapYhMapOutfall/detail",
        name:"雨污混合排放口",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psPoint
    },

    'SPP':{
        url:"/yhsw-map/mapYhMapSupplypipe/detail",
        name:"供水管线",
        system:"供水",
        imgUrl:"/static/img/IntelligentDrainage/供水0.png",
        info:commonPropertiesConfig.gsLine
    },

    'USR':{
        url:"/yhsw-map/mapYhMapUser/detail",
        name:"用户",
        system:"供水",
        imgUrl:"/static/img/IntelligentDrainage/供水0.png",
        info:commonPropertiesConfig.gsPoint
    },
    'SVA':{
        url:"/yhsw-map/mapYhMapValve/detail",
        name:"供水阀门",
        system:"供水",
        imgUrl:"/static/img/IntelligentDrainage/供水0.png",
        info:commonPropertiesConfig.gsPoint
    },
    'YVA':{
        url:"/yhsw-map/mapYhMapValve/detail",
        name:"雨水阀门",
        system:"雨水",
        imgUrl:"/static/img/IntelligentDrainage/雨水0.png",
        info:commonPropertiesConfig.gsPoint
    },
    'WVA':{
        url:"/yhsw-map/mapYhMapValve/detail",
        name:"污水阀门",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psPoint
    },
    'HVA':{
        url:"/yhsw-map/mapYhMapValve/detail",
        name:"雨污混合阀门",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psPoint
    },

    'SWW':{
        url:"/yhsw-map/mapYhMapWaterWork/detail",
        name:"自来水厂",
        system:"供水",
        imgUrl:"/static/img/IntelligentDrainage/供水0.png",
        info:commonPropertiesConfig.gsPoint
    },
    'WTP':{
        url:"/yhsw-map/mapYhMapWwtp/detail",
        name:"污水厂",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psPoint
    },

    'MTB':{
        url:"/yhsw-map/mapYhMapMeterbox/detail",
        name:"水表箱",
        system:"供水",
        imgUrl:"/static/img/IntelligentDrainage/供水0.png",
        info:commonPropertiesConfig.gsPoint
    },
    'BTB':{
        url:"/yhsw-map/mapYhMapMeterbox/detail",
        name:"大表",
        system:"供水",
        imgUrl:"/static/img/IntelligentDrainage/供水0.png",
        info:commonPropertiesConfig.gsPoint
    },
    'DSC':{
        url:"/yhsw-map/mapYhMapUser/detail",
        name:"排水户",
        system:"供水",
        imgUrl:"/static/img/IntelligentDrainage/供水0.png",
        info:commonPropertiesConfig.gsPoint
    },

    'SMT':{
        url:"/yhsw-map/mapYhMapMonitor/detail",
        name:"供水监测点",
        system:"供水",
        imgUrl:"/static/img/IntelligentDrainage/供水0.png",
        info:commonPropertiesConfig.gsPoint
    },
    'YMT':{
        url:"/yhsw-map/mapYhMapMonitor/detail",
        name:"雨水监测点",
        system:"雨水",
        imgUrl:"/static/img/IntelligentDrainage/雨水0.png",
        info:commonPropertiesConfig.psPoint
    },
    'WMT':{
        url:"/yhsw-map/mapYhMapMonitor/detail",
        name:"污水监测点",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psPoint
    },
    'HMT':{
        url:"/yhsw-map/mapYhMapMonitor/detail",
        name:"雨污混合监测点",
        system:"污水",
        imgUrl:"/static/img/IntelligentDrainage/污水0.png",
        info:commonPropertiesConfig.psPoint
    },
}
export function getDeviceType(deviceId){
    if (deviceId) {
        let type = deviceId.slice(0,3);
        return TypeList[type]
    }
    return ""
}
export function getInfoByName (name) {
    let key = Object.keys(TypeList).find(key => TypeList[key].name === name);
    return key? TypeList[key].info : []
}

